trigger:
  branches:
    include:
      - '*' # Triggers on all branches

pr:
  branches:
    include:
      - main # Run pipeline for PRs targeting main

variables:
  awsServiceConnection: 'aws-oidc-federation'
  awsRegion: 'us-east-1'
  cloudFormationTemplatePath: '$(System.DefaultWorkingDirectory)/azure-cft-project-1/Ec2CFT.yaml'
  cloudFormationStackName: 'MyEC2CftStack'

jobs:
- job: CI
  displayName: 'Continuous Integration - Validate CloudFormation'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    displayName: 'Checkout Code'

  - script: |
      if [ ! -f "$(cloudFormationTemplatePath)" ]; then
        echo "Error: CloudFormation template not found at $(cloudFormationTemplatePath)"
        exit 1
      fi
    displayName: 'Check if CloudFormation Template Exists'

  - task: AWSShellScript@1
    displayName: 'Validate CloudFormation Template'
    inputs:
      awsCredentials: '$(awsServiceConnection)'
      regionName: '$(awsRegion)'
      scriptType: 'inline'
      inlineScript: |
        aws cloudformation validate-template --template-body file://$(cloudFormationTemplatePath)

- job: CD
  displayName: 'Continuous Deployment - Deploy to AWS'
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    displayName: 'Checkout Code for CD'

  - script: |
      echo "Deploying CloudFormation stack: $(cloudFormationStackName)"
      echo "Template Path: $(cloudFormationTemplatePath)"
      echo "AWS Region: $(awsRegion)"
    displayName: 'Log Deployment Details'

  - task: AWSShellScript@1
    displayName: 'Create/Update CloudFormation Stack'
    inputs:
      awsCredentials: '$(awsServiceConnection)'
      regionName: '$(awsRegion)'
      scriptType: 'inline'
      inlineScript: |
        aws cloudformation deploy \
          --template-file $(cloudFormationTemplatePath) \
          --stack-name $(cloudFormationStackName) \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset